#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    bootstrap_before = 'myspacevim#before'
    file_searching_tools = ['fd', 'fd --type file --hidden --follow --exclude .git']
    autocomplete_method = "coc"
    vimcompatible = true
    project_rooter_outermost = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"
auto_completion_enable_snippers_in_popup = true

[[layers]]
name = "checkers"
enable = false

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 50

[[layers]]
name = 'git'
git_plugin = 'fugitive'

[[layers]]
name = 'fzf'

[[layers]]
name = 'lang#html'
emmet_leader_key = "<C-e>"

[[custom_plugins]]
repo = "https://github.com/tpope/vim-unimpaired"
merged = false

[[custom_plugins]]
repo = "https://github.com/tpope/vim-abolish"
merged = false

[[custom_plugins]]
repo = "https://github.com/nelstrom/vim-visual-star-search"
merged = false

[[custom_plugins]]
repo = "https://github.com/tpope/vim-obsession"
merged = false

[[custom_plugins]]
repo = "https://github.com/junegunn/fzf.vim"
merged = false

[[custom_plugins]]
repo = "https://github.com/christoomey/vim-tmux-navigator"
merged = false

[[custom_plugins]]
repo = "https://github.com/haya14busa/incsearch.vim"
merged = false

[[custom_plugins]]
repo = "https://github.com/haya14busa/incsearch-easymotion.vim"
merged = false

[[custom_plugins]]
repo = "https://github.com/terryma/vim-multiple-cursors"
merged = false

[[custom_plugins]]
repo = "https://github.com/vim-scripts/argtextobj.vim"
merged = false

[[custom_plugins]]
repo = "https://github.com/tommcdo/vim-exchange"
merged = false

[[custom_plugins]]
repo = "https://github.com/kana/vim-textobj-entire"
merged = false

[[custom_plugins]]
repo = "https://github.com/dbakker/vim-paragraph-motion"
merged = false

[[custom_plugins]]
repo = "https://github.com/mileszs/ack.vim"
merged = false

[[custom_plugins]]
repo = "https://github.com/mattn/emmet-vim"
merged = false

[[custom_plugins]]
repo = "https://github.com/tyru/open-browser.vim"
merged = false

[[custom_plugins]]
repo = "https://github.com/dhruvasagar/vim-zoom"
merged = false
